/*
 * Copyright (C) 2017 Metazone Infotech Pvt Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.mz.advisell.gui;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.mz.advisell.bean.Investment;
import org.mz.advisell.services.SchemeService;
import org.mz.advisell.services.InvestmentService;

/**
 *
 * @author parii
 */
public class RecordInvestmentDialog extends javax.swing.JDialog {

    private final String aadhar;
    /**
     * Creates new form InvestmentDialog
     *
     * @param parent
     * @param modal
     * @param aadhar
     */
    public RecordInvestmentDialog(java.awt.Frame parent, boolean modal, String aadhar) {
        super(parent, modal);
        initComponents();
        addInvestmentPanel();
        this.aadhar = aadhar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyLbl = new javax.swing.JLabel();
        investmentLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        investmentPanel = new javax.swing.JPanel();
        moreBtn = new javax.swing.JButton();
        investmentResultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Investment");
        setResizable(false);

        companyLbl.setText("Select Company Name");

        investmentLbl.setText("Investment");

        investmentPanel.setLayout(new javax.swing.BoxLayout(investmentPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(investmentPanel);

        moreBtn.setText("+");
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        investmentResultLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        investmentResultLbl.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(investmentResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(companyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(investmentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moreBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(investmentResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investmentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed
        addInvestmentPanel();
    }//GEN-LAST:event_moreBtnActionPerformed
    
    public int validateInvestment(JTextField investmentTextField){
        investmentResultLbl.setText("");
        
        if(investmentTextField.getText().trim().isEmpty()){
            investmentResultLbl.setText("Please fill investment...");
        }else if(!investmentTextField.getText().trim().matches("[0-9]*")){
            investmentResultLbl.setText("Invalid!!!");
        }else if(investmentTextField.getText().trim().length()>Integer.MAX_VALUE){
            investmentResultLbl.setText("Out of range");
        }
        
        if(investmentResultLbl.getText().isEmpty()){
            return 1;
        }else{
            return 0;
        }
    }
    
    private void addInvestmentBtnActionPerformed(java.awt.event.ActionEvent evt) {
        JPanel currentInvestmentPanel = (JPanel)((JButton)evt.getSource()).getParent();
        JTextField investmentTextField = (JTextField)currentInvestmentPanel.getComponent(1);
        JComboBox schemesDropDown = (JComboBox)currentInvestmentPanel.getComponent(0);
        
        int result=validateInvestment(investmentTextField);
        if(result==0){
            return;
        }
        
        Investment investment = new Investment();
        investment.setAmount(Integer.parseInt(investmentTextField.getText()));
        investment.setScheme(schemesDropDown.getSelectedItem().toString()); 
        InvestmentService investmentService = new InvestmentService();
        result = investmentService.addInvestment(investment, aadhar);
        if (result > 0) {
            investmentResultLbl.setText("successfully added.");
        } else {
            investmentResultLbl.setText("Error in making investment.");
        }
    }
    
    private void addInvestmentPanel() {
        JPanel singleInvestmentPanel = new JPanel();
        singleInvestmentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        JComboBox schemesDropDown = new JComboBox();
        SchemeService schemeService = new SchemeService();
        ArrayList<String> schemeList = schemeService.getSchemes();
        for (String scheme : schemeList) {
            schemesDropDown.addItem(scheme);
        }
        JTextField amountTextField = new JTextField();
        amountTextField.setName("amount");
        JButton addInvestmentBtn = new JButton("Add");
        javax.swing.GroupLayout singleInvestmentPanelLayout = new javax.swing.GroupLayout(singleInvestmentPanel);
        singleInvestmentPanel.setLayout(singleInvestmentPanelLayout);
        singleInvestmentPanelLayout.setHorizontalGroup(
                singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleInvestmentPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(schemesDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addInvestmentBtn)
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        singleInvestmentPanelLayout.setVerticalGroup(
                singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleInvestmentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(schemesDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addInvestmentBtn))
                                .addContainerGap(0, Short.MAX_VALUE))
        );
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addInvestmentBtn.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInvestmentBtnActionPerformed(evt);
            }
        });
        investmentPanel.add(singleInvestmentPanel, 0);
        revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyLbl;
    private javax.swing.JLabel investmentLbl;
    private javax.swing.JPanel investmentPanel;
    private javax.swing.JLabel investmentResultLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moreBtn;
    // End of variables declaration//GEN-END:variables
}
