/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.irt;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.mz.irt.bo.company.CompanyBo;
import org.mz.irt.bo.company.CompanyBoImp1;
import org.mz.irt.buttoncolumn.ButtonColumn;

/**
 *
 * @author parii
 */
public class CompanyPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompanyPanel
     */
    public CompanyPanel() {
        initComponents();
        //generateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyNameTextField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        companyNameLbl = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        companyNameTable = new javax.swing.JTable();

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        companyNameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        companyNameLbl.setText("Company :");

        companyNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(companyNameTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int row = companyNameTable.getSelectedRow();
        CompanyBo companyBo = new CompanyBoImp1();
        if (addBtn.getText().equals("Add")) {
            int result = companyBo.addCompanyName(companyNameTextField.getText().toUpperCase());
            if (result > 0) {
                resultLbl.setText("Add Successfully");
            } else {
                resultLbl.setText("Can not be added");
            }
        } else {
            int result = companyBo.updateCompanyName((String) companyNameTable.getValueAt(row, 1),companyNameTextField.getText().toUpperCase());
            if (result > 0) {
                addBtn.setText("Add");
                resultLbl.setText("Modified Successfully");
            } else {
                resultLbl.setText("Can not be modified");
            }
        }
        generateTable();
    }//GEN-LAST:event_addBtnActionPerformed

    public void generateTable() {
        CompanyBo companyBo = new CompanyBoImp1();
        ArrayList<String> companyNameList = companyBo.getCompaniesName();
        String[] columns = new String[]{"S.No.", "Company Name", "Edit", "Delete"};
        DefaultTableModel tableModel = new DefaultTableModel(0, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column > 1) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        tableModel.setColumnIdentifiers(columns);
        companyNameTable.setModel(tableModel);
        for (int count = 1; count <= companyNameList.size(); count++) {
            tableModel.addRow(new Object[]{String.valueOf(count), companyNameList.get(count - 1)});
        }
        companyNameTable.setRowHeight(30);
        Action btn = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        companyNameTextField.setText((String) companyNameTable.getValueAt(companyNameTable.getSelectedRow(), 1));
                        addBtn.setText("Save");
                        companyNameTextField.requestFocus();
                    }
                });
            }
        };
        Action btn1 = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        int row = companyNameTable.getSelectedRow();
                        CompanyBo companyBo = new CompanyBoImp1();
                        int result = companyBo.deleteCompanyName((String) companyNameTable.getValueAt(row, 1));
                        if (result > 0) {
                            resultLbl.setText("Delete Successfully");
                        } else {
                            resultLbl.setText("Error");
                        }
                        generateTable();
                    }
                });
            }
        };
        new ButtonColumn(companyNameTable, btn, 2);
        new ButtonColumn(companyNameTable, btn1, 3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel companyNameLbl;
    private javax.swing.JTable companyNameTable;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLbl;
    // End of variables declaration//GEN-END:variables
}
