/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.irt;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.mz.irt.model.Profile;
import org.mz.irt.bo.profile.ProfileBo;
import org.mz.irt.bo.profile.ProfileBoImp1;
import org.mz.irt.model.Document;

/**
 *
 * @author metazone
 */
public class EditProfilePanel extends javax.swing.JPanel {
    //String gender;
    private final JFrame frame;
    private Profile profile;
    private JLabel previewDocumentLbl;
    ArrayList<Document> documentList = new ArrayList<Document>();
    int i, component;
    /**
     * Creates new form FilePanel
     */
    public EditProfilePanel(JFrame frame,Profile profile) {
        this.profile=profile;
        this.frame = frame;
        initComponents();
        firstNameTextField.setText(profile.getFirstName());
        lastNameTextField.setText(profile.getLastName());
        contactNumberTextField.setText(profile.getContactNumber());
        phoneNumberTextField.setText(profile.getPhoneNumber());
        i=profile.getDocumentList().size()-1;
//        if(profile.getGender().equals("male")){
//            maleRadioBtn.setSelected(true);
//        }else{
//            femaleRadioBtn.setSelected(true);
//        }
        panNoTextField.setText(profile.getPanNumber());
        emailIdTextField.setText(profile.getEmailId());
        addressTextField.setText(profile.getAddress());
//        cityTextField.setText(profile.getCity());
//        stateTextField.setText(profile.getState());
//        pinNoTextField.setText(profile.getPinNumber());
        aadharTextField.setText(profile.getAadharCardNumber());
//        for(Document document:profile.getDocumentList()){
//           createDocumentPanel();
//           String filePath="documents/" + profile.getAadharCardNumber()+document.getFileName();
//           previewDocumentLbl.setIcon(new ImageIcon(scaledImage(new ImageIcon(filePath).getImage(), previewDocumentLbl.getWidth(), previewDocumentLbl.getHeight())));
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        profileTitleLbl = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        contactNumberLbl = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        emailIdLbl = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        addressLbl = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        aadharLbl = new javax.swing.JLabel();
        aadharTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        msgLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        phoneNumberLbl = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        panNoLbl = new javax.swing.JLabel();
        panNoTextField = new javax.swing.JTextField();
        documentsPanel = new javax.swing.JPanel();

        //genderButtonGroup.add(maleRadioBtn);
        //genderButtonGroup.add(femaleRadioBtn);

        profileTitleLbl.setText("Profile");

        firstNameLbl.setText("First Name");

        lastNameLbl.setText("Last Name");

        contactNumberLbl.setText("Contact Number");

        emailIdLbl.setText("EmailId");

        addressLbl.setText("Address");

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        aadharLbl.setText("Aadhar Card No");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("+91");

        phoneNumberLbl.setText("PhoneNumber");

        panNoLbl.setText("Pan Number");

        javax.swing.GroupLayout documentsPanelLayout = new javax.swing.GroupLayout(documentsPanel);
        documentsPanel.setLayout(documentsPanelLayout);
        documentsPanelLayout.setHorizontalGroup(
            documentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        documentsPanelLayout.setVerticalGroup(
            documentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(279, 279, 279))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(contactNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(phoneNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(profileTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(msgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aadharLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aadharTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(documentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(profileTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(msgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panNoTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aadharLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aadharTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(documentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Profile profile=new Profile();
        profile.setFirstName(firstNameTextField.getText());
        profile.setLastName(lastNameTextField.getText());
        profile.setContactNumber(contactNumberTextField.getText());
//        if(gender!=null){
//            profile.setGender(gender);
//        }else{
//           profile.setGender(this.profile.getGender()); 
//        }
        profile.setEmailId(emailIdTextField.getText());
        profile.setAddress(addressTextField.getText());
//        profile.setCity(cityTextField.getText());
//        profile.setState(stateTextField.getText());
//        profile.setPinNumber(pinNoTextField.getText());
        profile.setAadharCardNumber(aadharTextField.getText());
        ProfileBo profileBo=new ProfileBoImp1();
        int result=profileBo.updateProfile(profile);
        if(result>0){
            msgLbl.setText("Profile modified successfully");
            //frame.setEnabled(true);
            this.getTopLevelAncestor().setVisible(false);
        }else{
            msgLbl.setText("Profile does not modified");  
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed
    
    private void uploadDocument() {
        i++;
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
        Document document = new Document();
        document.setFile(file);
        int index = file.getName().indexOf(".");
        document.setFileName("document_" + i + file.getName().substring(index));
//        FilenameFilter filter = new FilenameFilter() {
//            public boolean accept(File file,String name) {
//                return name.endsWith(".jpg") || name.endsWith(".pdf");
//            }
//        };
        documentList.add(document);
//        ClientProfileUploadDocumentBo uploadDocumentBo = new ClientProfileUploadDocumentBoImp1();
//        uploadDocumentBo.uploadDocument(document,aadharTextField.getText());
//        try {
//          JTextArea textArea=new JTextArea();
//          previewDocumentPanel.add(textArea);
//          System.out.println(file.getName());
//         FileReader fileReader=new FileReader(file);
//          System.out.println(fileReader);
//          textArea.read(fileReader,file);
//        } catch (IOException ex) {
//          System.out.println("problem accessing file"+file.getAbsolutePath());
//        }
        ImageIcon icon = new ImageIcon(filePath);
        Image img = icon.getImage();
        previewDocumentLbl.setIcon(new ImageIcon(scaledImage(img, previewDocumentLbl.getWidth(), previewDocumentLbl.getHeight())));
        createDeleteButton();
        createDocumentPanel();
    }
    
    private Image scaledImage(Image img, int width, int height) {
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics g = bufferedImage.createGraphics();
        g.drawImage(img, 0, 0, height, width, null);
        return bufferedImage;
    }

    private void createDeleteButton() {
        JPanel deletePanel = (JPanel) ((JPanel) documentsPanel.getComponent(component - 1)).getComponent(2);
        JButton deleteBtn = new JButton("Delete");
        deletePanel.add(deleteBtn);
        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                documentsPanel.remove(deleteBtn.getParent().getParent());
            }
        });
    }
    
    
    private void createDocumentPanel() {
        JPanel documentPanel = new JPanel();
        JLabel previewDocumentLbl = new JLabel();
        this.previewDocumentLbl = previewDocumentLbl;
        JPanel deleteBtnPanel = new JPanel();
        JButton uploadDocumentBtn = new JButton("Upload Documents");
        GroupLayout documentPanelLayout = new GroupLayout(documentPanel);
        documentPanel.setLayout(documentPanelLayout);
        documentPanelLayout.setHorizontalGroup(
                documentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(documentPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(uploadDocumentBtn)
                                .addGap(49, 49, 49)
                                .addComponent(previewDocumentLbl, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                                //.addGap(69, 69, 69)
                                .addComponent(deleteBtnPanel, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE))
        );
        documentPanelLayout.setVerticalGroup(
                documentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(documentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(documentPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(uploadDocumentBtn, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(previewDocumentLbl, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteBtnPanel, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        uploadDocumentBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uploadDocument();
            }
        });
//        deleteBtn.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                documentsPanel.remove(documentPanel);
//            }
//        });
        documentsPanel.add(documentPanel);
        component++;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadharLbl;
    private javax.swing.JTextField aadharTextField;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel contactNumberLbl;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JPanel documentsPanel;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JLabel panNoLbl;
    private javax.swing.JTextField panNoTextField;
    private javax.swing.JLabel phoneNumberLbl;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel profileTitleLbl;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
