/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.irt;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.mz.irt.bo.profile.ProfileBo;
import org.mz.irt.bo.profile.ProfileBoImp1;
import org.mz.irt.bo.uploadDocument.ClientProfileUploadDocumentBo;
import org.mz.irt.bo.uploadDocument.ClientProfileUploadDocumentBoImp1;
import org.mz.irt.model.Document;
import org.mz.irt.model.Profile;

/**
 *
 * @author Saket
 */
public class NewProfileDialog extends javax.swing.JDialog {

    //private final JFrame frame;
    private JLabel previewDocumentLbl;
    String gender;
    ArrayList<Document> documentList = new ArrayList<Document>();
    int i;
    /**
     * Creates new form NewProfileDialog
     */
    public NewProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //this.frame = parent;
        initComponents();
        //createDocumentPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msgLbl = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        mobilePanel = new javax.swing.JPanel();
        contactNumberLbl = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        phonePanel = new javax.swing.JPanel();
        phoneNumberLbl = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        emailPanel = new javax.swing.JPanel();
        emailIdLbl = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        addressLbl = new javax.swing.JLabel();
        addressScrollPane = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        aadharPanel = new javax.swing.JPanel();
        aadharLbl = new javax.swing.JLabel();
        aadharTextField = new javax.swing.JTextField();
        panPanel = new javax.swing.JPanel();
        panNoLbl = new javax.swing.JLabel();
        panNoTextField = new javax.swing.JTextField();
        documentsPanel = new javax.swing.JPanel();
        uploadLbl = new javax.swing.JLabel();
        createprofileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Profile");
        setIconImage(new ImageIcon(getClass().getResource("icon_new_profile.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Profile", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(387, 205));

        firstNameLbl.setText("First Name");

        lastNameLbl.setText("Last Name");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(firstNameTextField))
                .addGap(10, 10, 10)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(lastNameTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mobilePanel.setLayout(new java.awt.GridLayout(2, 1));

        contactNumberLbl.setText("Mobile");
        mobilePanel.add(contactNumberLbl);

        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        mobilePanel.add(contactNumberTextField);

        phonePanel.setLayout(new java.awt.GridLayout(2, 1));

        phoneNumberLbl.setText("Phone");
        phonePanel.add(phoneNumberLbl);

        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        phonePanel.add(phoneNumberTextField);

        emailPanel.setLayout(new java.awt.GridLayout(2, 1));

        emailIdLbl.setText("Email");
        emailPanel.add(emailIdLbl);
        emailPanel.add(emailIdTextField);

        addressLbl.setText("Address");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        addressScrollPane.setViewportView(addressTextArea);

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addressScrollPane)
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addressScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        aadharPanel.setLayout(new java.awt.GridLayout(2, 1));

        aadharLbl.setText("Aadhar Card No");
        aadharPanel.add(aadharLbl);
        aadharPanel.add(aadharTextField);

        panPanel.setLayout(new java.awt.GridLayout(2, 1));

        panNoLbl.setText("Pan No");
        panPanel.add(panNoLbl);
        panPanel.add(panNoTextField);

        documentsPanel.setLayout(new javax.swing.BoxLayout(documentsPanel, javax.swing.BoxLayout.LINE_AXIS));

        uploadLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mz/irt/plus_upload.png"))); // NOI18N
        uploadLbl.setBorder(javax.swing.BorderFactory.createDashedBorder(Color.GRAY));
        documentsPanel.add(uploadLbl);

        createprofileBtn.setText("Create Profile");
        createprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createprofileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(documentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aadharPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phonePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mobilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(msgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mobilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(aadharPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(documentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createprofileBtn)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void createprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createprofileBtnActionPerformed
        i=0;
        Profile profile = new Profile();
        profile.setFirstName(firstNameTextField.getText());
        profile.setLastName(lastNameTextField.getText());
        profile.setContactNumber(contactNumberTextField.getText());
        profile.setPhoneNumber(phoneNumberTextField.getText());
        //profile.setGender(gender);
        profile.setEmailId(emailIdTextField.getText());
        profile.setAddress(addressTextArea.getText());
        //profile.setCity(cityTextField.getText());
        //profile.setState(stateTextField.getText());
        //profile.setPinNumber(pinNoTextField.getText());
        profile.setAadharCardNumber(aadharTextField.getText());
        profile.setPanNumber(panNoTextField.getText());
        ProfileBo profileBo = new ProfileBoImp1();
        if (!(documentList.isEmpty())) {
            ClientProfileUploadDocumentBo uploadDocumentBo = new ClientProfileUploadDocumentBoImp1();
            uploadDocumentBo.uploadDocument(documentList, aadharTextField.getText());
        }
        profile.setDocumentList(documentList);
        int result = profileBo.createProfile(profile);
        if (result > 0) {
            msgLbl.setText("Profile created");
            //frame.setEnabled(true);
            //this.getTopLevelAncestor().setVisible(false);
        } else {
            msgLbl.setText("Profile does not created");
        }
    }//GEN-LAST:event_createprofileBtnActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void uploadDocument() {
        i++;
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
        Document document = new Document();
        document.setFile(file);
        int index=file.getName().indexOf(".");
        document.setFileName("document_"+i+"."+file.getName().substring(index));
//        FilenameFilter filter = new FilenameFilter() {
//            public boolean accept(File file,String name) {
//                return name.endsWith(".jpg") || name.endsWith(".pdf");
//            }
//        };
        documentList.add(document);
//        ClientProfileUploadDocumentBo uploadDocumentBo = new ClientProfileUploadDocumentBoImp1();
//        uploadDocumentBo.uploadDocument(document,aadharTextField.getText());
//        try {
//          JTextArea textArea=new JTextArea();
//          previewDocumentPanel.add(textArea);
//          System.out.println(file.getName());
//         FileReader fileReader=new FileReader(file);
//          System.out.println(fileReader);
//          textArea.read(fileReader,file);
//        } catch (IOException ex) {
//          System.out.println("problem accessing file"+file.getAbsolutePath());
//        }
        ImageIcon icon = new ImageIcon(filePath);
        Image img = icon.getImage();
        previewDocumentLbl.setIcon(new ImageIcon(scaledImage(img, previewDocumentLbl.getWidth(), previewDocumentLbl.getHeight())));
        createDocumentPanel();
    }

    void deleteDocument() {
        
    }

    private Image scaledImage(Image img, int width, int height) {
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics g = bufferedImage.createGraphics();
        g.drawImage(img, 0, 0, height, width, null);
        return bufferedImage;
    }

    private void createDocumentPanel() {
        JPanel documentPanel = new JPanel();
        JLabel previewDocumentLbl = new JLabel();
        this.previewDocumentLbl = previewDocumentLbl;
        JButton deleteBtn = new JButton("Delete");
        JButton uploadDocumentBtn = new JButton("Upload Documents");
        GroupLayout documentPanelLayout = new GroupLayout(documentPanel);
        documentPanel.setLayout(documentPanelLayout);
        documentPanelLayout.setHorizontalGroup(
                documentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(documentPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(uploadDocumentBtn)
                                .addGap(49, 49, 49)
                                .addComponent(previewDocumentLbl, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                                //.addGap(69, 69, 69)
                                .addComponent(deleteBtn, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(160, Short.MAX_VALUE))
        );
        documentPanelLayout.setVerticalGroup(
                documentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(documentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(documentPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(uploadDocumentBtn, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(previewDocumentLbl, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteBtn, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        uploadDocumentBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                uploadDocument();
            }
        });
        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteDocument();
            }
        });
        documentsPanel.add(documentPanel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadharLbl;
    private javax.swing.JPanel aadharPanel;
    private javax.swing.JTextField aadharTextField;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel contactNumberLbl;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JButton createprofileBtn;
    private javax.swing.JPanel documentsPanel;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel mobilePanel;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel panNoLbl;
    private javax.swing.JTextField panNoTextField;
    private javax.swing.JPanel panPanel;
    private javax.swing.JLabel phoneNumberLbl;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JLabel uploadLbl;
    // End of variables declaration//GEN-END:variables
}
