/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.irt;

import com.sun.prism.j2d.J2DPipeline;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.mz.irt.bo.profile.ProfileBo;
import org.mz.irt.bo.profile.ProfileBoImp1;
import org.mz.irt.bo.search.SearchBo;
import org.mz.irt.bo.search.SearchBoImp1;
import org.mz.irt.model.Profile;

/**
 *
 * @author metazone
 */
public class SearchPanel extends javax.swing.JPanel {

    private final JFrame frame;

    /**
     * Creates new form GetAadharPanel
     */
    public SearchPanel(JFrame frame) {
        this.frame = frame;
        initComponents();
        //searchOnChange();
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchOnChange();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchOnChange();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchLbl = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        investmentResultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientListPanel = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Saket Kumar Malik");

        jLabel2.setText("+91-8510080900");

        jButton1.setText("Edit");

        jButton2.setText("Invest");

        jButton3.setText("Delete");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("HCL Extra Life");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)
                        .addGap(18, 43, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(6, 6, 6))
        );

        searchLbl.setText("Search with Name/Contact/Aadhar/PAN");

        clientListPanel.setLayout(new javax.swing.BoxLayout(clientListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(clientListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTextField)
                    .addComponent(searchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(investmentResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(searchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investmentResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void searchOnChange() {
        SearchBo searchBo = new SearchBoImp1();
        ArrayList<Profile> clientList = searchBo.getClientList(searchTextField.getText());
        clientListPanel.removeAll();
        if (!(clientList.isEmpty())) {
            for (Profile clientDetails : clientList) {
                JPanel clientPanel = new JPanel();
                clientPanel.setEnabled(true);
                clientPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                clientPanel.setBorder(BorderFactory.createLineBorder(Color.BLUE));
                JLabel clientNameLbl = new JLabel();
                JLabel clientPhoneNumberLbl = new JLabel();
                JLabel clientEmailIdLbl = new JLabel();
                JLabel clientAadharLbl = new JLabel();
                JLabel clientPanNoLbl = new JLabel();
                JButton editBtn = new JButton("Edit");
                JButton deleteBtn = new JButton("Delete");
                JButton investmentBtn = new JButton("Investment");
                clientNameLbl.setText(clientDetails.getFirstName() + " " + clientDetails.getLastName());
                clientPhoneNumberLbl.setText(clientDetails.getContactNumber());
                clientEmailIdLbl.setText(clientDetails.getEmailId());
                clientPanNoLbl.setText(clientDetails.getPanNumber());
                clientAadharLbl.setText(clientDetails.getAadharCardNumber());
                GroupLayout clientPanelLayout = new GroupLayout(clientPanel);
                clientPanel.setLayout(clientPanelLayout);
                clientPanelLayout.setHorizontalGroup(
                        clientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(clientPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(clientNameLbl, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientPanNoLbl, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientPhoneNumberLbl, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientEmailIdLbl, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clientAadharLbl, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editBtn, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(deleteBtn, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(investmentBtn)
                                        .addContainerGap(180, Short.MAX_VALUE))
                );
                clientPanelLayout.setVerticalGroup(
                        clientPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(clientPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(clientNameLbl, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(clientPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(editBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(deleteBtn, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(investmentBtn, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clientAadharLbl, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                         .addComponent(clientPanNoLbl, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clientEmailIdLbl, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clientPhoneNumberLbl, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(62, Short.MAX_VALUE))
                );

                investmentBtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        investment(clientDetails);
                    }
                });

                deleteBtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        deleteProfile(clientDetails);
                    }
                });

                editBtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        editProfile(clientDetails);
                    }
                });

                clientPanel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        viewProfile(clientDetails);
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {

                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {

                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        clientPanel.setBackground(new Color(0, 204, 204));
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        clientPanel.setBackground(new Color(240, 240, 240));
                    }
                });
                clientListPanel.add(clientPanel);
            }
            revalidate();
        }
    }

    private void editProfile(Profile client) {
        JDialog dialog = new JDialog(frame, true);
        dialog.add(new EditProfilePanel(frame, client));
        dialog.setSize(575, 650);
        dialog.setVisible(true);
        searchOnChange();
    }

    private void viewProfile(Profile client) {
        new ProfileDialog(frame, true, client).setVisible(true);
    }

    private void deleteProfile(Profile client) {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure want to delete this profile", "Confirmation Dialog", dialogButton);
        if (dialogResult == JOptionPane.OK_OPTION) {
            ProfileBo profileBo = new ProfileBoImp1();
            int result = profileBo.deleteProfile(client.getAadharCardNumber());
            if (result > 0) {
                investmentResultLbl.setText("Delete successfully");
                searchOnChange();
            } else {
                investmentResultLbl.setText("Error");
            }
        }
    }

    private void investment(Profile client) {
        JDialog dialog = new JDialog(frame, true);
        dialog.add(new InvestmentPanel(frame, client.getAadharCardNumber()));
        dialog.setSize(450, 400);
        dialog.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientListPanel;
    private javax.swing.JLabel investmentResultLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
