/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.advisell.gui;

import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.text.NumberFormatter;
import org.mz.advisell.bo.company.CompanyBo;
import org.mz.advisell.bo.company.CompanyBoImp1;
import org.mz.advisell.bo.makeInvestment.MakeInvestmentBo;
import org.mz.advisell.bo.makeInvestment.MakeInvestmentBoImp1;

/**
 *
 * @author metazone
 */
public class InvestmentPanel extends javax.swing.JPanel {
    private final JFrame frame;
    private final String aadharNo;
    /**
     * Creates new form GetAadharPanel
     */
    public InvestmentPanel(JFrame frame,String aadharNo) {
        this.frame = frame;
        this.aadharNo=aadharNo;
        initComponents();
        JPanel makeInvestmentPanel = createPanel();
        investmentPanel.add(makeInvestmentPanel);
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyLbl = new javax.swing.JLabel();
        investmentLbl = new javax.swing.JLabel();
        investmentResultLbl = new javax.swing.JLabel();
        moreBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        investmentPanel = new javax.swing.JPanel();
        singleInvestmentPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        singleInvestmentPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        singleInvestmentPanel2 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();

        companyLbl.setText("Select Company Name");

        investmentLbl.setText("Investment");

        moreBtn.setText("+");
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        investmentPanel.setLayout(new javax.swing.BoxLayout(investmentPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HCL", "HP", "DELL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setText("20,000");

        jButton1.setText("Add");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HCL", "HP", "DELL" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setText("20,000");

        jButton2.setText("Add");

        javax.swing.GroupLayout singleInvestmentPanel1Layout = new javax.swing.GroupLayout(singleInvestmentPanel1);
        singleInvestmentPanel1.setLayout(singleInvestmentPanel1Layout);
        singleInvestmentPanel1Layout.setHorizontalGroup(
            singleInvestmentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        singleInvestmentPanel1Layout.setVerticalGroup(
            singleInvestmentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(singleInvestmentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout singleInvestmentPanelLayout = new javax.swing.GroupLayout(singleInvestmentPanel);
        singleInvestmentPanel.setLayout(singleInvestmentPanelLayout);
        singleInvestmentPanelLayout.setHorizontalGroup(
            singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addComponent(singleInvestmentPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        singleInvestmentPanelLayout.setVerticalGroup(
            singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleInvestmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(singleInvestmentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        investmentPanel.add(singleInvestmentPanel);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HCL", "HP", "DELL" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jFormattedTextField3.setText("20,000");

        jButton3.setText("Add");

        javax.swing.GroupLayout singleInvestmentPanel2Layout = new javax.swing.GroupLayout(singleInvestmentPanel2);
        singleInvestmentPanel2.setLayout(singleInvestmentPanel2Layout);
        singleInvestmentPanel2Layout.setHorizontalGroup(
            singleInvestmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );
        singleInvestmentPanel2Layout.setVerticalGroup(
            singleInvestmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleInvestmentPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(singleInvestmentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        investmentPanel.add(singleInvestmentPanel2);

        jScrollPane1.setViewportView(investmentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addComponent(investmentResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(investmentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(moreBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(investmentResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(investmentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private JPanel createPanel() {
        JPanel makeInvestmentPanel = new JPanel();
        JComboBox companyNameDropDown = new JComboBox();
        CompanyBo companyBo=new CompanyBoImp1();
        ArrayList<String> companyNameList=companyBo.getCompaniesName();
        for(String companyName:companyNameList)
        companyNameDropDown.addItem(companyName);
        //companyNameDropDown.setSize(20, 20);
        NumberFormatter formatter = new NumberFormatter(); 
        formatter.setAllowsInvalid(false); 
        JFormattedTextField investmentTextField = new JFormattedTextField(formatter);
        JButton addInvestmentBtn = new JButton("Add");
        addInvestmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeInvestmentBo makeInvestmentBo = new MakeInvestmentBoImp1();
                int result = makeInvestmentBo.addInvestment(companyNameDropDown.getSelectedItem().toString(), investmentTextField.getText(),aadharNo);
                if (result > 0) {
                    investmentResultLbl.setText("successfully added");
                } else {
                    investmentResultLbl.setText("Error to make investment");
                }
            }
        });
        GroupLayout makeInvestmentPanelLayout = new GroupLayout(makeInvestmentPanel);
        makeInvestmentPanel.setLayout(makeInvestmentPanelLayout);
        makeInvestmentPanelLayout.setHorizontalGroup(
                makeInvestmentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(makeInvestmentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(companyNameDropDown, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(investmentTextField, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addInvestmentBtn, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makeInvestmentPanelLayout.setVerticalGroup(
                makeInvestmentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(makeInvestmentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(makeInvestmentPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(companyNameDropDown, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(investmentTextField, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addInvestmentBtn, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        return makeInvestmentPanel;
    }
    
    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed
        JPanel makeInvestmentPanel = createPanel();
        //investmentPanel.setSize(new Dimension(investmentPanel.getPreferredSize().width,investmentPanel.getPreferredSize().height));
        //JScrollPane scrollPane=new JScrollPane(investmentPanel);
        //investmentPanel.setLayout(new BoxLayout(investmentPanel,BoxLayout.Y_AXIS));
        //scrollPane.setLocation(20,100);
        //this.add(scrollPane);
        investmentPanel.add(makeInvestmentPanel);
        revalidate();
        //this.getTopLevelAncestor().setSize(400,this.getTopLevelAncestor().getHeight()+150);
        //JScrollPane scrollPane=new JScrollPane();
        //scrollPane.setAutoscrolls(true);
        //scrollPane.add(investmentPanel);
        //makeInvestPanel.setMinimumSize(new Dimension(makeInvestPanel.getPreferredSize().width,makeInvestPanel.getPreferredSize().height));
        //makeInvestPanel.setMaximumSize(new Dimension(makeInvestPanel.getPreferredSize().width,120));
        //investmentPanel.add(makeInvestPanel);
        //System.out.println(investmentPanel.getWidth()+" "+investmentPanel.getHeight());
        //makeInvestPanel.setSize(makeInvestPanel.getWidth(),makeInvestPanel.getHeight());
        //makeInvestPanel.setLocation(makeInvestmentPanel.getX(),makeInvestmentPanel.getY());
        //investmentPanel.setSize(investmentPanel.getWidth(),investmentPanel.getHeight()+makeInvestmentPanel.getHeight()+20);
        //        System.out.println(investmentPanel.getWidth()+" "+investmentPanel.getHeight());
        //        makeInvestPanel.setSize(makeInvestmentPanel.getWidth(),makeInvestmentPanel.getHeight());
        //        makeInvestPanel.setLocation(makeInvestmentPanel.getX(),makeInvestmentPanel.getY()+20);
        //        investmentPanel.add(makeInvestPanel);
        //        System.out.println(moreBtn.getX()+" "+moreBtn.getY());
        //        System.out.println(makeInvestmentPanel.getWidth()+" "+makeInvestmentPanel.getHeight());
        //        moreBtn.setLocation(moreBtn.getX(),investmentPanel.getY()+20);
        //        makeInvestmentPanel.setLocation(moreBtn.getX(),moreBtn.getY()-35);
        //        moreBtn.setLocation(makeInvestmentPanel.getX(),makeInvestmentPanel.getY()+50);
        //        System.out.println(makeInvestmentPanel.getX()+" "+makeInvestmentPanel.getY());
        //        moreBtn.setLocation(moreBtn.getX(),moreBtn.getY()+150);
        //        investmentPanel.setSize(investmentPanel.getWidth(),investmentPanel.getHeight()+100);
        //        makeInvestmentPanel.setSize(investmentPanel.getWidth(),90);
        //        makeInvestmentPanel.setLocation(,);
        //        investmentPanel.add(makeInvestPanel);
        //        makeInvestmentPanel.setBounds(moreBtn.getX(),moreBtn.getY(),400,100);
        //        moreBtn.setLocation(moreBtn.getX(),moreBtn.getY()+20);
        //        moreBtn.setLocation();
        //        moreBtn.setBounds(moreBtn.getX(),moreBtn.getY()+20, moreBtn.getWidth(),moreBtn.getHeight());
        //        moreBtn.setBounds(20,150,10,10);
        //        System.out.println(moreBtn.getX()+" "+moreBtn.getY());
        //
    }//GEN-LAST:event_moreBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyLbl;
    private javax.swing.JLabel investmentLbl;
    private javax.swing.JPanel investmentPanel;
    private javax.swing.JLabel investmentResultLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moreBtn;
    private javax.swing.JPanel singleInvestmentPanel;
    private javax.swing.JPanel singleInvestmentPanel1;
    private javax.swing.JPanel singleInvestmentPanel2;
    // End of variables declaration//GEN-END:variables
}
