/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.advisell.gui;

import javax.swing.JDialog;
import javax.swing.JFrame;
import org.mz.advisell.model.Profile;

/**
 *
 * @author parii
 */
public class MessageDialog extends javax.swing.JPanel {
    private final JFrame frame;
    private final Profile client;
    /**
     * Creates new form MessageDialog
     */
    public MessageDialog(JFrame frame,Profile client) {
        initComponents();
        this.frame=frame;
        this.client=client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        investNowBtn = new javax.swing.JButton();
        laterBtn = new javax.swing.JButton();

        investNowBtn.setText("Invest now");
        investNowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investNowBtnActionPerformed(evt);
            }
        });

        laterBtn.setText("Later");
        laterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(investNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(laterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void investNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investNowBtnActionPerformed
       JDialog dialog = new JDialog(frame, true);
        dialog.add(new InvestmentPanel(frame, client.getAadharCardNumber()));
        dialog.setSize(450, 400);
        dialog.setVisible(true); 
    }//GEN-LAST:event_investNowBtnActionPerformed

    private void laterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laterBtnActionPerformed
       this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_laterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton investNowBtn;
    private javax.swing.JButton laterBtn;
    // End of variables declaration//GEN-END:variables
}
