/*
 * Copyright (C) 2017 Metazone Infotech Pvt Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.mz.advisell.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.mz.advisell.bo.profile.ProfileBo;
import org.mz.advisell.services.ProfileService;
import org.mz.advisell.bo.search.SearchBo;
import org.mz.advisell.services.SearchService;
import org.mz.advisell.services.ClientProfileUploadDocumentBo;
import org.mz.advisell.services.DocumentService;
import org.mz.advisell.bean.Profile;

/**
 *
 * @author metazone
 */
public class SearchPanel extends javax.swing.JPanel {

    private final Frame frame;
    private Profile profile;

    /**
     * Creates new form GetAadharPanel
     */
    public SearchPanel(java.awt.Frame frame) {
        this.frame = frame;
        initComponents();
        showClientResult();
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                showClientResult();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                showClientResult();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singleResultPanel = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        mobileLbl = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        investmentBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        schemeLbl = new javax.swing.JLabel();
        searchLbl = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        investmentResultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientListPanel = new javax.swing.JPanel();

        singleResultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        singleResultPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLbl.setText("Saket Kumar Malik");

        mobileLbl.setText("+91-8510080900");

        editBtn.setText("Edit");

        investmentBtn.setText("Invest");

        deleteBtn.setText("Delete");

        schemeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        schemeLbl.setText("HCL Extra Life");

        javax.swing.GroupLayout singleResultPanelLayout = new javax.swing.GroupLayout(singleResultPanel);
        singleResultPanel.setLayout(singleResultPanelLayout);
        singleResultPanelLayout.setHorizontalGroup(
            singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(singleResultPanelLayout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(investmentBtn)
                        .addGap(18, 43, Short.MAX_VALUE)
                        .addComponent(deleteBtn))
                    .addGroup(singleResultPanelLayout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(mobileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(schemeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        singleResultPanelLayout.setVerticalGroup(
            singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleResultPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(mobileLbl)
                    .addComponent(schemeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investmentBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn))
                .addGap(6, 6, 6))
        );

        searchLbl.setText("Search with Name/Contact/Aadhar/PAN");

        investmentResultLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        investmentResultLbl.setForeground(new java.awt.Color(255, 0, 0));

        clientListPanel.setLayout(new javax.swing.BoxLayout(clientListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(clientListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTextField)
                    .addComponent(searchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(investmentResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(searchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investmentResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    public void showClientResult() {
        SearchBo searchBo = new SearchService();
        ArrayList<Profile> clientList = searchBo.getClientList(searchTextField.getText());
        clientListPanel.removeAll();
        if (!(clientList.isEmpty())) {
            for (Profile profile : clientList) {
                this.profile = profile;
                JPanel singleResultPanel = createSingleResult();
                singleResultPanel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        singleResultPanelMouseClicked(evt);
                    }
                });
                clientListPanel.add(singleResultPanel);
            }
            revalidate();
        }
    }

    private JPanel createSingleResult() {
        JPanel singleResultPanel = new JPanel();
        singleResultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        singleResultPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButton deleteBtn = new JButton();
        JButton editBtn = new JButton();
        JButton investmentBtn = new JButton();
        JLabel mobileLbl = new JLabel();
        JLabel nameLbl = new JLabel();
        JLabel schemeLbl = new JLabel();

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLbl.setText(profile.getFirstName() + " " + profile.getLastName());
        mobileLbl.setText(profile.getContactNumber());
        editBtn.setText("Edit");
        investmentBtn.setText("Invest");
        deleteBtn.setText("Delete");
        schemeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        schemeLbl.setText("HCL Extra Life");

        javax.swing.GroupLayout singleResultPanelLayout = new javax.swing.GroupLayout(singleResultPanel);
        singleResultPanel.setLayout(singleResultPanelLayout);
        singleResultPanelLayout.setHorizontalGroup(
                singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(investmentBtn)
                                                .addGap(18, 43, Short.MAX_VALUE)
                                                .addComponent(deleteBtn))
                                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(mobileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(schemeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        singleResultPanelLayout.setVerticalGroup(
                singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLbl)
                                        .addComponent(mobileLbl)
                                        .addComponent(schemeLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(investmentBtn)
                                        .addComponent(editBtn)
                                        .addComponent(deleteBtn))
                                .addGap(6, 6, 6))
        );
        investmentBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                investmentBtnActionPerformed(evt);
            }
        });

        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        editBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        return singleResultPanel;
    }
    
    private void singleResultPanelMouseClicked(java.awt.event.MouseEvent evt){
        new ViewProfileDialog(frame, true, profile).setVisible(true);
        showClientResult();
    }
    
    private void editBtnActionPerformed(ActionEvent evt) {
        //new FillProfileDialog(frame, true).setVisible(true);
        showClientResult();
    }

    private void deleteBtnActionPerformed(ActionEvent evt) {
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure want to delete this profile", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.OK_OPTION) {
            ProfileBo profileBo = new ProfileService();
            int result = profileBo.deleteProfile(profile.getAadharCardNumber());
            if (result > 0) {
                ClientProfileUploadDocumentBo uploadDocumentBo = new DocumentService();
                uploadDocumentBo.deleteDocuments(profile.getAadharCardNumber());
                investmentResultLbl.setText("Delete successfully");
                showClientResult();
            } else {
                investmentResultLbl.setText("Error");
            }
        }
    }

    private void investmentBtnActionPerformed(ActionEvent evt) {
        new RecordInvestmentDialog(frame, true, profile.getAadharCardNumber()).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientListPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton investmentBtn;
    private javax.swing.JLabel investmentResultLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel schemeLbl;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel singleResultPanel;
    // End of variables declaration//GEN-END:variables
}
