/*
 * Copyright (C) 2017 Metazone Infotech Pvt Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.mz.advisell.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.mz.advisell.services.ProfileService;
import org.mz.advisell.services.SearchService;
import org.mz.advisell.services.DocumentService;
import org.mz.advisell.bean.Profile;
import org.mz.advisell.bean.ProfilePreview;
import org.mz.advisell.constant.Constant;

/**
 *
 * @author metazone
 */
public class SearchPanel extends javax.swing.JPanel {

    private SearchService searchService;

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        searchService = new SearchService();
        showClientResults(searchService.getClientList(searchTextField.getText()));
        /**
         * Document Listener is used to implement event on text change
         * in Search TextField
         */
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                showClientResults(searchService.getClientList(searchTextField.getText()));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                showClientResults(searchService.getClientList(searchTextField.getText()));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singleResultPanelDesign = new javax.swing.JPanel();
        nameLblDesign = new javax.swing.JLabel();
        mobileLblDesign = new javax.swing.JLabel();
        editBtnDesign = new javax.swing.JButton();
        investmentBtnDesign = new javax.swing.JButton();
        deleteBtnDesign = new javax.swing.JButton();
        searchLbl = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchResultLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientListPanel = new javax.swing.JPanel();

        singleResultPanelDesign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        singleResultPanelDesign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nameLblDesign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLblDesign.setText("Saket Kumar Malik");

        mobileLblDesign.setText("+91-8510080900");

        editBtnDesign.setText("Edit");

        investmentBtnDesign.setText("Invest");

        deleteBtnDesign.setText("Delete");

        javax.swing.GroupLayout singleResultPanelDesignLayout = new javax.swing.GroupLayout(singleResultPanelDesign);
        singleResultPanelDesign.setLayout(singleResultPanelDesignLayout);
        singleResultPanelDesignLayout.setHorizontalGroup(
            singleResultPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleResultPanelDesignLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleResultPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(singleResultPanelDesignLayout.createSequentialGroup()
                        .addComponent(editBtnDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(investmentBtnDesign)
                        .addGap(18, 43, Short.MAX_VALUE)
                        .addComponent(deleteBtnDesign))
                    .addGroup(singleResultPanelDesignLayout.createSequentialGroup()
                        .addComponent(nameLblDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(mobileLblDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        singleResultPanelDesignLayout.setVerticalGroup(
            singleResultPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleResultPanelDesignLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(singleResultPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLblDesign)
                    .addComponent(mobileLblDesign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(singleResultPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investmentBtnDesign)
                    .addComponent(editBtnDesign)
                    .addComponent(deleteBtnDesign))
                .addGap(6, 6, 6))
        );

        searchLbl.setText("Search with Name/Contact/Aadhar/PAN");

        searchResultLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchResultLbl.setForeground(new java.awt.Color(255, 0, 0));

        clientListPanel.setLayout(new javax.swing.BoxLayout(clientListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(clientListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTextField)
                    .addComponent(searchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(searchResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(searchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void showClientResults(ArrayList<ProfilePreview> clientList) {
        clientListPanel.removeAll();
        for (ProfilePreview profilePreview : clientList) {
            JPanel singleResultPanel = createSingleResult(profilePreview);
            singleResultPanel.putClientProperty(Constant.AADHAR_KEY, profilePreview.getAadharCardNumber());/*Aadhar is linked to every result*/
            singleResultPanel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    singleResultPanelMouseClicked(evt);
                }
            });
            clientListPanel.add(singleResultPanel);
        }
        revalidate();
    }

    private JPanel createSingleResult(ProfilePreview profilePreview) {
        JPanel singleResultPanel = new JPanel();
        singleResultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        singleResultPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButton deleteBtn = new JButton();
        JButton editBtn = new JButton();
        JButton investmentBtn = new JButton();
        JLabel mobileLbl = new JLabel();
        JLabel nameLbl = new JLabel();

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLbl.setText(profilePreview.getFirstName() + " " + profilePreview.getLastName());
        mobileLbl.setText(profilePreview.getMobileNumber());
        editBtn.setText("Edit");
        investmentBtn.setText("Invest");
        deleteBtn.setText("Delete");

        javax.swing.GroupLayout singleResultPanelLayout = new javax.swing.GroupLayout(singleResultPanel);
        singleResultPanel.setLayout(singleResultPanelLayout);
        singleResultPanelLayout.setHorizontalGroup(
                singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(investmentBtn)
                                                .addGap(18, 43, Short.MAX_VALUE)
                                                .addComponent(deleteBtn))
                                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(mobileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())
        );
        singleResultPanelLayout.setVerticalGroup(
                singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(singleResultPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLbl)
                                        .addComponent(mobileLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(singleResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(investmentBtn)
                                        .addComponent(editBtn)
                                        .addComponent(deleteBtn))
                                .addGap(6, 6, 6))
        );
        investmentBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                investmentBtnActionPerformed(evt);
            }
        });

        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        editBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        return singleResultPanel;
    }
    
    private void singleResultPanelMouseClicked(java.awt.event.MouseEvent evt){
        String aadhar = (String)((JPanel)evt.getComponent()).getClientProperty(Constant.AADHAR_KEY);
        Profile profile = new ProfileService().getClientDetails(aadhar);
        new ViewProfileDialog((javax.swing.JFrame)this.getTopLevelAncestor(), true, profile).setVisible(true);
    }
    
    private void editBtnActionPerformed(ActionEvent evt) {
        String aadhar = (String)((JPanel)((JButton)evt.getSource()).getParent()).getClientProperty(Constant.AADHAR_KEY);
        Profile profile = new ProfileService().getClientDetails(aadhar);
        new FillProfileDialog((javax.swing.JFrame)this.getTopLevelAncestor(), true, profile).setVisible(true);
    }

    private void deleteBtnActionPerformed(ActionEvent evt) {
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure want to delete this profile", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.OK_OPTION) {
            String aadhar = (String)((JPanel)((JButton)evt.getSource()).getParent()).getClientProperty(Constant.AADHAR_KEY);
            ProfileService profileService = new ProfileService();
            int result = profileService.deleteProfile(aadhar);
            if (result > 0) {
                DocumentService documentService = new DocumentService();
                documentService.deleteDocuments(aadhar);
                searchResultLbl.setText("Deleted successfully.");
                clientListPanel.remove((JPanel)((JButton)evt.getSource()).getParent());
                this.getTopLevelAncestor().revalidate();
            } else {
                searchResultLbl.setText("Error! Please try again.");
            }
        }
    }

    private void investmentBtnActionPerformed(ActionEvent evt) {
        String aadhar = (String)((JPanel)((JButton)evt.getSource()).getParent()).getClientProperty(Constant.AADHAR_KEY);
        new RecordInvestmentDialog((javax.swing.JFrame)this.getTopLevelAncestor(), true, aadhar).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientListPanel;
    private javax.swing.JButton deleteBtnDesign;
    private javax.swing.JButton editBtnDesign;
    private javax.swing.JButton investmentBtnDesign;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileLblDesign;
    private javax.swing.JLabel nameLblDesign;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JLabel searchResultLbl;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel singleResultPanelDesign;
    // End of variables declaration//GEN-END:variables
}
