/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mz.advisell.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.mz.advisell.model.Document;
import org.mz.advisell.model.Profile;

/**
 *
 * @author Saket
 */
public class ViewProfileDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public ViewProfileDialog(java.awt.Frame parent, boolean modal, Profile profile) {
        super(parent, modal);
        initComponents();
        
        /*nameLbl.setText(profile.getFirstName()+" "+profile.getLastName());
        contactNumberLbl.setText(profile.getContactNumber());
        mobileNoLbl.setText(profile.getPhoneNumber());
        emailIdLbl.setText(profile.getEmailId());
        addressLbl.setText(profile.getAddress());
        panNoLbl.setText(profile.getPanNumber());
        aadharCardLbl.setText(profile.getAadharCardNumber());
        for(Document document:profile.getDocumentList()){
            createDocument(document,profile);
        }
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        aadharLbl = new javax.swing.JLabel();
        aadharNo = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        phoneNo = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        investBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        emailIdLbl = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        mobileLbl = new javax.swing.JLabel();
        mobileNo = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        panNoLbl = new javax.swing.JLabel();
        panNo = new javax.swing.JLabel();
        investmentLbl = new javax.swing.JLabel();
        investment = new javax.swing.JLabel();
        documentLbl = new javax.swing.JLabel();
        documentsPanel = new javax.swing.JPanel();
        uploadLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(contentPanel.getPreferredSize());

        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLbl.setText("Saket Kumar Malik");

        aadharLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aadharLbl.setText("Aadhar:");

        aadharNo.setText("7898 7871 3509");

        phoneLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phoneLbl.setText("Phone:");

        phoneNo.setText("09813076033");

        editBtn.setText("Edit");

        investBtn.setText("Invest");

        deleteBtn.setText("Delete");

        emailIdLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailIdLbl.setText("Email:");

        email.setText("saketrtkmalik@gmail.com");

        mobileLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mobileLbl.setText("Mobile:");

        mobileNo.setText("+91-8510080900");

        addressLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressLbl.setText("Address:");

        address.setText("<html>46, Revenue Colony,Near Agro Mall, Rohtak Haryana-124001hjvhjbhjbhjvhjv jhbvhjvbhj hjkh jkb jkhkj h ljkljkl imkij  klkl  j");
        address.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        panNoLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panNoLbl.setText("PAN:");

        panNo.setText("DJTMR2346J");

        investmentLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        investmentLbl.setText("Investments:");

        investment.setText("<html>Cheque 42352 HDFC LC 23/07/1997<br>Cheque 42352 HDFC LC 23/07/1997<br>Cheque 42352 HDFC LC 23/07/1997<br>Cheque 42352 HDFC LC 23/07/1997 ");
        investment.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        documentLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        documentLbl.setText("Documents:");

        documentsPanel.setLayout(new javax.swing.BoxLayout(documentsPanel, javax.swing.BoxLayout.LINE_AXIS));

        uploadLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mz/advisell/gui/plus_upload.png"))); // NOI18N
        uploadLbl.setBorder(javax.swing.BorderFactory.createDashedBorder(Color.GRAY));
        documentsPanel.add(uploadLbl);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(investment)
                    .addComponent(documentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLbl)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(panNoLbl)
                                .addGap(26, 26, 26)
                                .addComponent(panNo))
                            .addComponent(investmentLbl)
                            .addComponent(documentLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(aadharLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aadharNo))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(emailIdLbl)
                                .addGap(18, 18, 18)
                                .addComponent(email))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(mobileLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mobileNo))
                            .addComponent(nameLbl)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(investBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aadharLbl)
                            .addComponent(aadharNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdLbl)
                            .addComponent(email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobileLbl)
                            .addComponent(mobileNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLbl)
                            .addComponent(phoneNo)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(investBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panNoLbl)
                    .addComponent(panNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investmentLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDocument(Document document,Profile profile) {
        JLabel documentLbl=new JLabel();
        documentLbl.setSize(120,215);
        String filePath = "documents/" + profile.getAadharCardNumber() + "/" + document.getFileName();
        documentLbl.setIcon(new ImageIcon(scaledImage(new ImageIcon(filePath).getImage(), 120, 215)));
        documentsPanel.add(documentLbl);
    }
    
    private Image scaledImage(Image img, int width, int height) {
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics g = bufferedImage.createGraphics();
        g.drawImage(img, 0, 0, height, width, null);
        return bufferedImage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadharLbl;
    private javax.swing.JLabel aadharNo;
    private javax.swing.JLabel address;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel documentLbl;
    private javax.swing.JPanel documentsPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JButton investBtn;
    private javax.swing.JLabel investment;
    private javax.swing.JLabel investmentLbl;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JLabel mobileNo;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel panNo;
    private javax.swing.JLabel panNoLbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JLabel uploadLbl;
    // End of variables declaration//GEN-END:variables
}
